import flet as ft


COLORS = [
    ft.Colors.AMBER,
    ft.Colors.BLACK,
    ft.Colors.BLUE,
    ft.Colors.BROWN,
    ft.Colors.CYAN,
    ft.Colors.CYAN_ACCENT,
    ft.Colors.DEEP_ORANGE,
    ft.Colors.DEEP_ORANGE_ACCENT,
    ft.Colors.DEEP_PURPLE,
    ft.Colors.DEEP_PURPLE_ACCENT,
    ft.Colors.GREEN,
    ft.Colors.GREEN_ACCENT,
    ft.Colors.GREY,
    ft.Colors.INDIGO,
    ft.Colors.INDIGO_ACCENT,
    # ft.Colors.INVERSE_PRIMARY,
    # ft.Colors.INVERSE_SURFACE,
    ft.Colors.LIGHT_BLUE,
    ft.Colors.LIGHT_BLUE_ACCENT,
    ft.Colors.LIGHT_GREEN,
    ft.Colors.LIGHT_GREEN_ACCENT,
    ft.Colors.LIME,
    ft.Colors.LIME_ACCENT,
    ft.Colors.ORANGE,
    ft.Colors.ORANGE_ACCENT,
    ft.Colors.PINK,
    ft.Colors.PINK_ACCENT,
    # ft.Colors.PRIMARY,
    ft.Colors.PURPLE,
    ft.Colors.PURPLE_ACCENT,
    ft.Colors.RED,
    ft.Colors.RED_ACCENT,
    # ft.Colors.SCRIM,
    # ft.Colors.SECONDARY,
    ft.Colors.TEAL,
    ft.Colors.TEAL_ACCENT,
    ft.Colors.TERTIARY,
    ft.Colors.YELLOW,
    ft.Colors.YELLOW_ACCENT,
]